### ISSUE TITLE
Initial Port is not configurable

### ISSUE THREAD

**Issue by maormann** [gerasimou/EvoChecker#11]
This line will always ensure that port 8888 is selected as INIT_PORT.

https://github.com/gerasimou/EvoChecker/blob/c2e8c5265d48a49bedb8485fa4e9192b82802f3d/src/main/java/evochecker/auxiliary/ConfigurationChecker.java#L106

Therefore, it is currently not possible to configure the initial port.

**Comment by gerasimou** [comment]
@maormann I believe this has been fixed in commit  [cda1a6f](https://github.com/gerasimou/EvoChecker/commit/cda1a6f95da953f5871f70247a7f21f65c59d731)

see https://github.com/gerasimou/EvoChecker/blob/master/src/main/java/evochecker/auxiliary/ConfigurationChecker.java#L90-L95

You may be using an older version?

**Comment by maormann** [comment]
Hey @gerasimou,
that is correct.
At the time I opened the ticket, the master branch was still at [c2e8c52](https://github.com/gerasimou/EvoChecker/commit/c2e8c5265d48a49bedb8485fa4e9192b82802f3d)

Here is the code of my pipeline that led to this version:
```
git clone https://github.com/gerasimou/EvoChecker.git evochecker || true && cd evochecker && mvn install
```

Seems commit [cda1a6f](https://github.com/gerasimou/EvoChecker/commit/cda1a6f95da953f5871f70247a7f21f65c59d731) was in the branch [newEC](https://github.com/gerasimou/EvoChecker/tree/newEC).

However. I have tested the latest version and the initial port is now set correctly.

So I see this Issue closed.

**Comment by gerasimou** [comment]
Thanks for the feedback @maormann. 

We are currently working on extending EvoChecker, so if you have any further points, please send them our way.
